"""Regenerates notebooks/stage2_remote.ipynb (Phase 5, runs 9-11).

Edit this, not the .ipynb, so the notebook stays diffable and free of execution
counts and stray outputs.

Same shape as the Phase 4 notebook: all the training logic lives in committed,
tested scripts and the notebook only clones and calls them. That is what makes
"runs 9 and 10 differ only in the CRF" a statement about a command line.
"""
import json
import pathlib


def md(*lines):
    return {"cell_type": "markdown", "metadata": {}, "source": [l + "\n" for l in lines]}


def code(*lines):
    return {"cell_type": "code", "execution_count": None, "metadata": {},
            "outputs": [], "source": [l + "\n" for l in lines]}


cells = [
    md("# Phase 5 - Stage 2 span extraction (Kaggle or Colab)",
       "",
       "Steps 5.4-5.6 of `PLAN.md`: runs 9-11 of the experiment matrix.",
       "",
       "| Run | Model | Varies | Step |",
       "|---|---|---|---|",
       "| 9 | BiLSTM + softmax | per-token decisions | 5.4 |",
       "| 10 | BiLSTM + **CRF** | Viterbi over learned transitions | 5.5 |",
       "| 11 | BiomedBERT token-cls | contextual | 5.6 |",
       "",
       "Steps 5.1-5.3 are already done: the BIO converter, its unit tests and the",
       "20-example spot-check are committed. Steps 5.7-5.9 (strict/lenient scoring,",
       "the illegal-sequence count, the published-corpus check) run **locally** after",
       "this notebook, from the prediction files it saves.",
       "",
       "**Accelerator: GPU T4 x2** (cell 1 pins one card). **Internet: On** for run",
       "11's checkpoint download.",
       "",
       "### What makes runs 9 and 10 a valid ablation",
       "",
       "They must differ *only* in `--crf`. Same embedding matrix (E3, the Phase 4",
       "winner), same seed, same hyperparameters, same split, same device count. The",
       "training script hard-fails if two GPUs are visible, because `DataParallel`",
       "changes both the effective batch and how the CRF loss is reduced -",
       "`pytorch-crf` computes its loss inside `forward`, so two devices return a",
       "loss vector rather than a scalar (`PLAN.md` F8)."),

    md("## 1. Environment, and the single-GPU pin (PLAN F8)",
       "",
       "**First cell, before `import torch`.** `CUDA_VISIBLE_DEVICES` is read once,",
       "when the CUDA context initialises; setting it after anything has touched",
       "`torch.cuda` is silently ignored for the rest of the kernel's life.",
       "",
       "### The one install - and the one that is deliberately absent",
       "",
       "`pytorch-crf` is pinned GROUP A and is not on the Kaggle base image.",
       "",
       "**`seqeval` is NOT installed here, and that is intentional.** Version 1.2.2 is",
       "its latest release (2020), it ships no wheel, and its legacy",
       "`setup.py egg_info` fails to build on this image's Python 3.12 -",
       "`metadata-generation-failed`. So Stage 2 scores entities with the native",
       "implementation in `src/stage2_metrics.py` instead, which needs nothing beyond",
       "the standard library. Locally, where seqeval does install, `entity_metrics`",
       "runs both and asserts they agree - verified to match exactly on strict and",
       "lenient F1, precision, recall and per-label scores across the whole corpus.",
       "",
       "It goes in through `sys.executable -m pip`, not `!pip`. On Kaggle the bare",
       "`!pip` resolves to whichever pip is first on PATH, which is not necessarily",
       "the interpreter running this kernel - so the install reports success and the",
       "very next `import` still raises `ModuleNotFoundError`. Installing through the",
       "running interpreter cannot miss it. The cell also checks the exit code and",
       "prints pip's output on failure, because `-q` otherwise hides the error that",
       "explains what went wrong."),

    code("import os",
         "",
         "# BEFORE importing torch. Not stylistic - see the note above.",
         "os.environ['CUDA_VISIBLE_DEVICES'] = '0'",
         "",
         "import sys, subprocess, pathlib, time",
         "",
         "ON_KAGGLE = pathlib.Path('/kaggle').exists()",
         "ON_COLAB = 'google.colab' in sys.modules or pathlib.Path('/content').exists()",
         "PLATFORM = 'kaggle' if ON_KAGGLE else 'colab' if ON_COLAB else 'local'",
         "WORK = pathlib.Path('/kaggle/working' if ON_KAGGLE else",
         "                    '/content' if ON_COLAB else '.')",
         "print('platform :', PLATFORM)",
         "print('kernel   :', sys.executable)",
         "",
         "# `!pip` resolves to whatever pip is first on PATH, which on Kaggle is not",
         "# always the interpreter running this kernel - so the install succeeds and",
         "# the import still fails. `sys.executable -m pip` cannot miss.",
         "# Output is captured and printed only on failure, because `-q` on a bare",
         "# `!pip` hides the error that explains what went wrong.",
         "result = subprocess.run(",
         "    [sys.executable, '-m', 'pip', 'install', '-q', 'pytorch-crf==0.7.2'],",
         "    capture_output=True, text=True)",
         "if result.returncode:",
         "    print(result.stdout[-4000:])",
         "    print(result.stderr[-4000:])",
         "    raise SystemExit('pip install failed - see the output above')",
         "print('installed : pytorch-crf')",
         "",
         "import torch, transformers, datasets, numpy",
         "import torchcrf   # just installed - fail here rather than mid-run",
         "from importlib.metadata import version",
         "",
         "print('torch', torch.__version__, '| transformers', transformers.__version__)",
         "print('pytorch-crf', version('pytorch-crf'))",

         "",
         "n = torch.cuda.device_count()",
         "print('CUDA devices visible:', n)",
         "print('GPU:', torch.cuda.get_device_name(0) if n else 'CPU')",
         "assert n <= 1, (",
         "    f'{n} GPUs visible - the pin did not take effect. Something touched "
         "torch.cuda '",
         "    'before this cell. Fix: Run -> Restart & clear cell outputs, then run "
         "THIS cell first.')",
         "",
         "print(f'\\nRECORD: torch={torch.__version__} "
         "transformers={transformers.__version__} devices={n}')"),

    md("## 2. Get the code",
       "",
       "The frozen splits are committed, so the clone brings the Stage 2 spans with",
       "it. The BIO tags are **not** committed - they are derived from those spans by",
       "`src/bio_convert.py` at the start of every run, which is what stops the",
       "converter and the training data drifting apart."),

    code("REPO_URL = 'https://github.com/sifatul-islam-onik/ADE-Sentinel.git'",
         "REPO = WORK / 'ADE-Sentinel'",
         "",
         "if not REPO.exists():",
         "    subprocess.run(['git', 'clone', '--depth', '1', REPO_URL, str(REPO)], check=True)",
         "else:",
         "    subprocess.run(['git', '-C', str(REPO), 'pull', '--ff-only'], check=False)",
         "",
         "sys.path.insert(0, str(REPO))",
         "os.chdir(REPO)",
         "GIT_COMMIT = subprocess.check_output(",
         "    ['git', '-C', str(REPO), 'rev-parse', '--short', 'HEAD'], text=True).strip()",
         "print('repo at', GIT_COMMIT)",
         "",
         "import pandas as pd",
         "for split in ('train', 'dev', 'test'):",
         "    df = pd.read_parquet(REPO / 'data' / 'splits' / f'stage2_{split}.parquet')",
         "    print(f'  stage2_{split}: {len(df):,} sentences, "
         "{df.n_spans.sum():,} spans')"),

    md("## 3. Test before training",
       "",
       "The tagger tests are skipped locally (no torch) and the CRF tests need",
       "`pytorch-crf`, so this is the first machine that can run either.",
       "",
       "The one that matters most is `test_crf_decode_honours_transition_scores`:",
       "it sets the illegal transitions to a large negative score and checks that",
       "Viterbi then never walks through them. That is the *mechanism* run 10 relies",
       "on. Note what it does **not** claim - `pytorch-crf` does not forbid any",
       "transition, so an untrained CRF can and does emit `I-DRUG` after `O`. The",
       "clean output in run 10 is learned from data, and the test is written to check",
       "the decoder rather than to assert a guarantee that does not exist."),

    code("tests = ['tests/test_bilstm_tagger.py', 'tests/test_stage2_metrics.py',",
         "         'tests/test_bio_convert.py']",
         "",
         "# -q keeps the passing output short; -x stops at the first failure so the",
         "# traceback that matters is the last thing printed rather than buried.",
         "result = subprocess.run([sys.executable, '-m', 'pytest', '-q', '-x'] + tests)",
         "if result.returncode:",
         "    raise SystemExit(",
         "        f'tests failed (exit {result.returncode}) - see the pytest output '",
         "        'directly above this message. Do not start the runs until it is "
         "green: '",
         "        'every number they produce depends on this code being correct.')",
         "print()",
         "print('all Stage 2 tests pass - safe to train')"),

    md("## 4. Embedding matrices",
       "",
       "Same Kaggle Dataset as Phase 4 - the `.npy` files are gitignored (`PLAN.md`",
       "F7), so cloning does not bring them. Attach the dataset via **Add Input** and",
       "put its version in `DATASET_VERSION`.",
       "",
       "Runs 9-10 use **E3 (FastText)**, which won the Phase 4 ablation at macro-F1",
       "0.8785 against 0.7942 for GloVe. `PLAN.md` 5.4 says \"best of E1-E3\"; that is",
       "what the four-bar chart selected."),

    code("DATASET_VERSION = ''   # <- the version shown in the Input panel",
         "",
         "import json, numpy as np",
         "",
         "",
         "def holds_matrices(d):",
         "    return d.is_dir() and (d / 'vocab.json').exists() and any(d.glob('E*.npy'))",
         "",
         "",
         "candidates = []",
         "if ON_KAGGLE:",
         "    root = pathlib.Path('/kaggle/input')",
         "    candidates += [p.parent for p in root.rglob('vocab.json')]",
         "    candidates += [root] + sorted(root.glob('*')) + sorted(root.glob('*/*'))",
         "candidates.append(REPO / 'models' / 'emb_matrices')",
         "",
         "MATRICES = next((d for d in candidates if holds_matrices(d)), None)",
         "if MATRICES is None:",
         "    listing = []",
         "    if ON_KAGGLE and pathlib.Path('/kaggle/input').exists():",
         "        for p in sorted(pathlib.Path('/kaggle/input').rglob('*'))[:40]:",
         "            listing.append(f'    {p}')",
         "    raise SystemExit(",
         "        'No directory with both vocab.json and E*.npy was found.\\n\\n'",
         "        'Mounted under /kaggle/input:\\n'",
         "        + ('\\n'.join(listing) if listing else '    (nothing attached)')",
         "        + '\\n\\nAttach the ade-sentinel-artifacts Dataset via Add Input.')",
         "",
         "print('matrices :', MATRICES)",
         "print('E3       :', np.load(MATRICES / 'E3.npy', mmap_mode='r').shape)",
         "if not DATASET_VERSION:",
         "    print('\\nWARNING: DATASET_VERSION is blank - the run rows lose their "
         "input provenance (PLAN F10)')"),

    md("## 5. Runs 9 and 10 - the CRF ablation",
       "",
       "One command each. **`--crf` is the only difference.**",
       "",
       "Watch the `illegal` column as the epochs print: run 9 will show a non-zero",
       "count that fluctuates, and run 10 should sit at exactly zero from the first",
       "epoch. That contrast is step 5.8, and it is visible during training rather",
       "than only at the end.",
       "",
       "A few minutes each on one T4."),

    code("def train_tagger(run_id, crf=False, **kw):",
         "    cmd = [sys.executable, 'scripts/train_bilstm_tagger.py',",
         "           '--run-id', str(run_id), '--embedding', 'E3',",
         "           '--matrices', str(MATRICES), '--dataset-version', DATASET_VERSION]",
         "    if crf:",
         "        cmd.append('--crf')",
         "    for k, v in kw.items():",
         "        cmd += [f'--{k.replace(\"_\", \"-\")}', str(v)]",
         "    print('\\n' + '=' * 70)",
         "    print(' '.join(cmd[1:]))",
         "    print('=' * 70)",
         "    subprocess.run(cmd, check=True)",
         "",
         "",
         "t0 = time.time()",
         "train_tagger('9', crf=False)",
         "train_tagger('10', crf=True)",
         "print(f'\\nruns 9-10 complete in {(time.time() - t0) / 60:.1f} min')"),

    md("## 6. Run 11 - BERT token classification",
       "",
       "BiomedBERT, the Phase 4 transformer winner (0.9402 against 0.9159 for",
       "bert-base-uncased).",
       "",
       "**The subword alignment is the whole risk here.** BIO tags are one per word;",
       "WordPiece splits words further. The script labels the first subword of each",
       "word, masks the rest with -100, and decodes predictions back to word level",
       "before scoring - so run 11's entity counts are comparable with runs 9-10.",
       "Scoring at subword level would make the same entity count for a different",
       "number of tokens, and the three runs would no longer be on one axis.",
       "",
       "Roughly 5-10 minutes on a T4."),

    code("cmd = [sys.executable, 'scripts/train_bert_tagger.py',",
         "       '--run-id', '11', '--model', 'biomedbert',",
         "       '--dataset-version', DATASET_VERSION]",
         "print(' '.join(cmd[1:]))",
         "t0 = time.time()",
         "subprocess.run(cmd, check=True)",
         "print(f'\\nrun 11 complete in {(time.time() - t0) / 60:.1f} min')"),

    md("## 7. Save the outputs - before the session ends",
       "",
       "| Artefact | Where it goes |",
       "|---|---|",
       "| `runs.csv` rows | **commit to git** |",
       "| `test_predictions.json` (all three runs) | **bring home** - steps 5.7-5.9 rescore from these locally, and Phase 6 needs them |",
       "| checkpoints | Kaggle Dataset; the BiLSTM-CRF one also ships in the Phase 7 demo |",
       "",
       "The prediction files are the important ones and they are small - a few",
       "hundred KB of tag strings. Everything in the report after this point is",
       "computed from them on the local machine, which is what makes the Stage 2",
       "numbers reproducible without a GPU."),

    code("import shutil",
         "",
         "bundle = WORK / 'phase5_outputs'",
         "if bundle.exists():",
         "    shutil.rmtree(bundle)",
         "bundle.mkdir()",
         "",
         "shutil.copy2('results/runs.csv', bundle / 'runs.csv')",
         "if pathlib.Path('models/stage2').exists():",
         "    shutil.copytree('models/stage2', bundle / 'stage2_models',",
         "                    ignore=shutil.ignore_patterns('trainer'))",
         "",
         "total = sum(f.stat().st_size for f in bundle.rglob('*') if f.is_file())",
         "print(f'{bundle}  ({total / 1e6:,.0f} MB)')",
         "for f in sorted(bundle.rglob('*')):",
         "    if f.is_file():",
         "        print(f'  {f.relative_to(bundle)}  {f.stat().st_size / 1e6:,.2f} MB')"),

    md("---",
       "",
       "## Then, locally - steps 5.7-5.9",
       "",
       "```bash",
       ".venv\\Scripts\\python scripts\\stage2_report.py",
       "```",
       "",
       "That rescores every run from the saved predictions, writes",
       "`results/figures/stage2_results.md` and the two-panel CRF figure, and checks",
       "the BIO conversion against the published corpus statistics. It also",
       "recomputes each logged entity-F1 independently and flags any disagreement -",
       "the remote session is trusted for the training, not for the numbers.",
       "",
       "## Phase 5 exit criterion",
       "",
       "From `PLAN.md`: the entity-F1 table is complete and the CRF illegal-sequence",
       "count is obtained.",
       "",
       "Read the result honestly:",
       "",
       "- **The CRF should drive illegal sequences to zero, or close to it.** This is",
       "  learned rather than enforced: the gold data contains no illegal transition,",
       "  so training pushes those scores down until Viterbi stops choosing them. A",
       "  small non-zero count is a legitimate result, not necessarily a bug.",
       "- **Entity-F1 may barely move between runs 9 and 10.** That is the expected",
       "  result and it is not a disappointment. Report both axes: on F1 the CRF looks",
       "  like a no-op, and the illegal-sequence count is where it earns its place.",
       "  A tagger whose output is always well-formed is the one you can put behind",
       "  the Phase 7 demo with no repair step.",
       "- **Run 11 should lead on F1.** If it does not, check the subword alignment",
       "  before concluding anything about transformers.",
       "",
       "Then Phase 6: run 12 chains the best Stage 1 model (run 8, BiomedBERT) into",
       "the best Stage 2 model on the shared test split - valid only because of the",
       "single global split (`PLAN.md` F4)."),
]

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

out = pathlib.Path(__file__).resolve().parents[1] / "notebooks" / "stage2_remote.ipynb"
out.write_text(json.dumps(nb, indent=1), encoding="utf-8")
print("wrote", out, len(cells), "cells")
