"""Step 1.5 - generate report/data_documentation.md from the corpus itself.

The PRD makes documenting the scraped corpus an explicit instructor requirement:
source, method, query, date range, volume. This generates that table by reading
the artefacts rather than by transcription, so the report cannot drift from what
was actually collected.

Run after the fetch completes:
    .venv\\Scripts\\python scripts\\document_corpus.py
"""

from __future__ import annotations

import json
import re
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from scripts.fetch_pubmed import (  # noqa: E402
    BASE, EFETCH_BATCH, MAX_YEAR, MIN_YEAR, PER_YEAR_CAP, QUERY, SHARD_DIR,
)

CORPUS = REPO_ROOT / "data" / "pubmed_corpus.jsonl"
OUT = REPO_ROOT / "report" / "data_documentation.md"

WORD = re.compile(r"[A-Za-z][A-Za-z0-9\-]*")


def main() -> int:
    if not CORPUS.exists():
        sys.exit(f"{CORPUS} not found - run the fetch first (notebooks/local_fetch.ipynb).")

    per_year = {}
    for shard in sorted(SHARD_DIR.glob("*.jsonl")):
        with shard.open(encoding="utf-8") as fh:
            per_year[shard.stem] = sum(1 for _ in fh)

    n = 0
    abstract_chars = 0
    title_chars = 0
    tokens = 0
    vocab: Counter[str] = Counter()
    empty_titles = 0

    with CORPUS.open(encoding="utf-8") as fh:
        for line in fh:
            rec = json.loads(line)
            n += 1
            abstract_chars += len(rec["abstract"])
            title_chars += len(rec["title"])
            if not rec["title"]:
                empty_titles += 1
            words = WORD.findall(f"{rec['title']} {rec['abstract']}".lower())
            tokens += len(words)
            vocab.update(words)

    size_mb = CORPUS.stat().st_size / 1e6
    fetched_at = datetime.fromtimestamp(
        max(p.stat().st_mtime for p in SHARD_DIR.glob("*.jsonl")), timezone.utc
    ).strftime("%Y-%m-%d")

    lines = [
        "# PubMed domain corpus - collection documentation",
        "",
        "Required by PRD section 6.2. Generated by `scripts/document_corpus.py` from the",
        "collected artefacts, so these figures cannot drift from what was actually",
        "fetched.",
        "",
        "## Collection parameters",
        "",
        "| Field | Value |",
        "|---|---|",
        "| Source | PubMed / MEDLINE, NCBI E-utilities |",
        f"| API base | `{BASE}` |",
        "| Method | `esearch` per date window -> `efetch` in batches of "
        f"{EFETCH_BATCH} (XML) |",
        f"| Query | `{QUERY}` |",
        f"| Date type | `pdat` (publication date) |",
        f"| Date range | {MIN_YEAR}/01/01 - {MAX_YEAR}/12/31 |",
        f"| Windowing | one `esearch` per year, subdivided into calendar months "
        f"when a year exceeds NCBI's 9,998-per-search cap |",
        f"| Per-year cap | {PER_YEAR_CAP:,} abstracts, split evenly across that "
        "year's windows |",
        "| Result ordering | `sort=pub_date` (NCBI's default relevance order is not "
        "stable, which would make a capped sample irreproducible) |",
        "| Rate limit | 10 req/s with an NCBI API key (3 without) |",
        f"| Collection date | {fetched_at} |",
        "| Storage | one JSONL file, `{\"pmid\", \"title\", \"abstract\"}` per line |",
        "",
        "## Volume",
        "",
        "| Measure | Value |",
        "|---|---|",
        f"| Abstracts collected | **{n:,}** |",
        f"| File size | {size_mb:,.1f} MB |",
        f"| Running words (title + abstract) | {tokens:,} |",
        f"| Vocabulary (distinct lowercase word forms) | {len(vocab):,} |",
        f"| Mean abstract length | {abstract_chars / n:,.0f} characters |",
        f"| Mean title length | {title_chars / n:,.0f} characters |",
        f"| Records with an empty title | {empty_titles:,} |",
        "",
        f"Clears the PRD's 100,000-abstract floor."
        if n >= 100_000 else
        f"**Below the PRD's 100,000-abstract floor ({n:,}).**",
        "",
        "## Distribution by publication year",
        "",
        "Even by construction: the per-year cap exists so the embedding corpus is not",
        "dominated by whichever years happen to be largest.",
        "",
        "| Year | Abstracts |",
        "|---|---|",
    ]
    for year, count in sorted(per_year.items()):
        lines.append(f"| {year} | {count:,} |")

    lines += [
        "",
        "## Two collection defects found and corrected",
        "",
        "Recorded because the collection process is itself part of what the report",
        "documents, and both were silent failures rather than errors.",
        "",
        "**1. `retstart` cannot exceed 9,998.** The PRD's sketch script pages with",
        "`retstart` in steps of 10,000. NCBI rejects that outright:",
        "",
        "```",
        "\"ERROR\":\"Search Backend failed: Exception: 'retstart' cannot be larger",
        " than 9998. For PubMed, ESearch can only retrieve the first 9,999 records\"",
        "```",
        "",
        "The script would have died on its second iteration with ~10k abstracts. Fixed",
        "by date windowing instead of offset paging.",
        "",
        "**2. February vanished from every non-leap year.** The first implementation",
        "built month windows from a hardcoded table with February ending on the 29th.",
        "In a non-leap year that is not a real date, and NCBI answers an impossible",
        "range with *zero results and no error*, so twelve of sixteen years silently",
        "lost a month. It surfaced only as an arithmetic tell: those years returned",
        "exactly 9,174 abstracts against 10,000 for leap years, a gap of 834 - precisely",
        "one window's share of the cap. Fixed with `calendar.monthrange`, and the",
        "affected years were refetched.",
        "",
        "## Intended use",
        "",
        "This corpus is unlabeled and is used only to train the domain embeddings",
        "(E2 Word2Vec, E3 FastText) that Section 7 of the PRD compares against",
        "general-purpose GloVe vectors. It carries no ADE annotations and is never",
        "used for supervised training or evaluation.",
        "",
    ]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")

    print(f"{n:,} abstracts | {tokens:,} tokens | {len(vocab):,} vocab | {size_mb:,.1f} MB")
    print(f"wrote {OUT.relative_to(REPO_ROOT)}")
    return 0 if n >= 100_000 else 2


if __name__ == "__main__":
    raise SystemExit(main())
